spring:
  profiles:
    active: local
    group:
      "local": "local"
      "prod": "prod"
      "docker": "docker"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: ${JWT_SECRET_KEY}

payment:
  mock:
    fail-rate: 0   # 0=항상 성공, 30=30% 실패, 100=항상 실패

toss:
  secret-key: ${TOSS_SECRET_KEY}